// Authentication Action Types
export const LOGIN_REQUESTED = 'LOGIN_REQUESTED',
  LOGIN_SUCCEEDED = 'LOGIN_SUCCEEDED',
  LOGIN_FAILED = 'LOGIN_FAILED',
  AUTH_USER = 'AUTH_USER',
  UNAUTH_USER = 'UNAUTH_USER',
  AUTH_ERROR = 'AUTH_ERROR',
  FORGOT_PASSWORD_REQUEST = 'FORGOT_PASSWORD_REQUEST',
  RESET_PASSWORD_REQUEST = 'RESET_PASSWORD_REQUEST',
  PROTECTED_TEST = 'PROTECTED_TEST';

// Create card action types
export const CREATE_CARD_REQUESTED = 'CREATE_CARD_REQUESTED',
  CREATE_CARD_FAILED = 'CREATE_CARD_FAILED',
  CREATE_CARD_SUCCEEDED = 'CREATE_CARD_SUCCEEDED',
  RETRIEVE_CARDS_SUCCEEDED = 'RETRIEVE_CARDS_SUCCEEDED',
  RETRIEVE_CARDS_FAILED = 'RETRIEVE_CARDS_FAILED',
  RETRIEVE_CARD_SUCCEEDED = 'RETRIEVE_CARD_SUCCEEDED',
  RETRIEVE_CARD_FAILED = 'RETRIEVE_CARD_SUCCEEDED',
  RETRIEVE_CARD_SUBJECT_SUCCEEDED = 'RETRIEVE_CARD_SUBJECT_SUCCEEDED',
  RETRIEVE_CARD_SUBJECT_FAILED = 'RETRIEVE_CARD_SUBJECT_FAILED',
  DELETE_CARD_FAILED = 'DELETE_CARD_FAILED',
  DELETE_CARD_SUCCEEDED = 'DELETE_CARD_SUCCEEDED',
  FILTER_CARDS = 'FILTER_CARDS',
  EDIT_CARD_FAILED = 'EDIT_CARD_FAILED',
  EDIT_CARD_SUCCEEDED = 'EDIT_CARD_SUCCEEDED';